apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: human-capital
  name: human-capital-placement-1
  namespace: human-capital
spec:
  clusterSelector:
    matchLabels:
      env: prod