apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/human-capital
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: human-capital
  name: human-capital-subscription-1
  namespace: human-capital
spec:
  channel: human-capital-channel/human-capital
  placement:
    placementRef:
      kind: PlacementRule
      name: human-capital-placement-1