apiVersion: v1
kind: Service
metadata:
  name: credit-initiation
  labels:
    app.kubernetes.io/name: credit-initiation
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: credit-initiation