apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/fraud-detection
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: fraud-detection
  name: fraud-detection-subscription-1
  namespace: fraud-detection
spec:
  channel: fraud-detection-channel/fraud-detection
  placement:
    placementRef:
      kind: PlacementRule
      name: fraud-detection-placement-1