apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: credit-initiation
  name: credit-initiation-placement-1
  namespace: credit-initiation
spec:
  clusterSelector:
    matchLabels:
      env: prod