apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/credit-initiation
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: credit-initiation
  name: credit-initiation-subscription-1
  namespace: credit-initiation
spec:
  channel: credit-initiation-channel/credit-initiation
  placement:
    placementRef:
      kind: PlacementRule
      name: credit-initiation-placement-1