apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/accounts-receivable
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: accounts-receivable
  name: accounts-receivable-subscription-1
  namespace: accounts-receivable
spec:
  channel: accounts-receivable-channel/accounts-receivable
  placement:
    placementRef:
      kind: PlacementRule
      name: accounts-receivable-placement-1