apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: accounting
  namespace: accounting-channel
spec:
  type: Git
  pathname: https://github.com/burrsutter/lotsofapps