apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/accounting
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: accounting
  name: accounting-subscription-1
  namespace: accounting
spec:
  channel: accounting-channel/accounting
  placement:
    placementRef:
      kind: PlacementRule
      name: accounting-placement-1