apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: manufacturing
  name: manufacturing-placement-1
  namespace: manufacturing
spec:
  clusterSelector:
    matchLabels:
      env: prod