apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/manufacturing
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: manufacturing
  name: manufacturing-subscription-1
  namespace: manufacturing
spec:
  channel: manufacturing-channel/manufacturing
  placement:
    placementRef:
      kind: PlacementRule
      name: manufacturing-placement-1