apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/client-onboarding
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: client-onboarding
  name: client-onboarding-subscription-1
  namespace: client-onboarding
spec:
  channel: client-onboarding-channel/client-onboarding
  placement:
    placementRef:
      kind: PlacementRule
      name: client-onboarding-placement-1