apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: distribution
  name: distribution-placement-1
  namespace: distribution
spec:
  clusterSelector:
    matchLabels:
      env: prod