apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/distribution
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: distribution
  name: distribution-subscription-1
  namespace: distribution
spec:
  channel: distribution-channel/distribution
  placement:
    placementRef:
      kind: PlacementRule
      name: distribution-placement-1