apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/finance
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: finance
  name: finance-subscription-1
  namespace: finance
spec:
  channel: finance-channel/finance
  placement:
    placementRef:
      kind: PlacementRule
      name: finance-placement-1