---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  labels:    
    app: fraud-detection
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: fraud-detection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection      
  template:
    metadata:
      labels:
        app: fraud-detection        
    spec:
      containers:
        - name: fraud-detection
          image: "docker.io/burrsutter/hello:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GREETING
              value: fraud-detection