apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/logistics
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: logistics
  name: logistics-subscription-1
  namespace: logistics
spec:
  channel: logistics-channel/logistics
  placement:
    placementRef:
      kind: PlacementRule
      name: logistics-placement-1