apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: visa-processor
  name: visa-processor-placement-1
  namespace: visa-processor
spec:
  clusterSelector:
    matchLabels:
      env: prod