apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/visa-processor
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: visa-processor
  name: visa-processor-subscription-1
  namespace: visa-processor
spec:
  channel: visa-processor-channel/visa-processor
  placement:
    placementRef:
      kind: PlacementRule
      name: visa-processor-placement-1