apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/plant-maintenance
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: plant-maintenance
  name: plant-maintenance-subscription-1
  namespace: plant-maintenance
spec:
  channel: plant-maintenance-channel/plant-maintenance
  placement:
    placementRef:
      kind: PlacementRule
      name: plant-maintenance-placement-1