apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: mastercard-processor
  name: mastercard-processor-placement-1
  namespace: mastercard-processor
spec:
  clusterSelector:
    matchLabels:
      env: prod