apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/mastercard-processor
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: mastercard-processor
  name: mastercard-processor-subscription-1
  namespace: mastercard-processor
spec:
  channel: mastercard-processor-channel/mastercard-processor
  placement:
    placementRef:
      kind: PlacementRule
      name: mastercard-processor-placement-1