apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange-placement-1
  namespace: currency-exchange
spec:
  clusterSelector:
    matchLabels:
      env: prod