apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/currency-exchange
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: currency-exchange
  name: currency-exchange-subscription-1
  namespace: currency-exchange
spec:
  channel: currency-exchange-channel/currency-exchange
  placement:
    placementRef:
      kind: PlacementRule
      name: currency-exchange-placement-1