apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: baseapp
  name: baseapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseapp
  template:
    metadata:
      labels:
        app: baseapp
    spec:
      containers:
      - image: docker.io/burrsutter/hello:1.0.0
        name: baseapp        
        ports:
        - containerPort: 8080
        env:
        - name: GREETING
          value: Aloha