apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: sales
  name: sales-placement-1
  namespace: sales
spec:
  clusterSelector:
    matchLabels:
      env: prod