---
# Source: baseapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sales
  labels:
    helm.sh/chart: baseapp-0.1.0
    app.kubernetes.io/name: baseapp
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: baseapp
    app.kubernetes.io/instance: release-name
---
# Source: baseapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  labels:
    helm.sh/chart: baseapp-0.1.0
    app.kubernetes.io/name: baseapp
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: baseapp
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: baseapp
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: baseapp
          image: "docker.io/burrsutter/hello:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GREETING
              value: sales
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {}
